version: "3.9"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: everlast_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d everlast_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    depends_on:
      db:
        condition: service_healthy
    command: ["/code/entrypoint.sh"]
    ports:
      - "8000:8000"

volumes:
  postgres_data:
